uso de binario para acceo directo independiente del appimage

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,16 +1,26 @@
-#!/bin/sh
+#!/bin/bash
+# postinst script for vx-dga-l-meshlab
 set -e
 
+case "$1" in
+    configure)
+        APPIMAGE="/usr/share/vitalinux/appimages/MeshLab2025.07-linux_x86_64.AppImage"
+        BINARIO="/usr/bin/vx-meshlab"
+
+        if [ -f "${APPIMAGE}" ]; then
+            chmod +x "${APPIMAGE}"
+            ln -sf "${APPIMAGE}" "${BINARIO}" || echo "No se puede crear el enlace al binario..."
+        else
+            echo "Hubo un error con la APP..."
+        fi
+    ;;
+    abort-upgrade | abort-remove | abort-deconfigure) ;;
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 1
+    ;;
+esac
+
 #DEBHELPER#
-
-if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ]; then
-    if ls /usr/lib/meshlab/*.AppImage >/dev/null 2>&1; then
-        chmod +x /usr/lib/meshlab/*.AppImage || true
-    fi
-
-    if [ -x /usr/bin/update-desktop-database ]; then
-        update-desktop-database -q /usr/share/applications || true
-    fi
-fi
 
 exit 0
